version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:1.1.2-sdk-jessie
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test ./test/Chroma.NetCore.Api.Tests/Chroma.NetCore.Api.Tests.csproj --no-build --filter Category=UnitTest
